### ISSUE TITLE
422 Unprocessable Entity for chat_token

### ISSUE THREAD

**Issue by danieleds** [signalwire/swrooms#1]
I get unprocessable_entity when asking for a chat token

```
curl 'https://guides.swrooms.com/public/chat_token' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json' \
  --data-raw '{"member_id":"my-unique-id","channels":{"my-channel-name":{"read":true,"write":true}}, "state":{}}'
```

Could this be related to this line here? https://github.com/signalwire/swrooms/blob/main/backend/routes/swPublicRoutes.js#L147

@niravcodes

**Comment by niravcodes** [comment]
There seems to be minor discrepancies between the implementation of the Chat API and its docs. Just like how the `content` attribute was listed as `message` attribute in the docs (now fixed), the `user_id` is listed as `member_id`.

@edolix I don't know whether you are planning to stick to the terminology in the docs or the one you originally described. What should I consider as the truth? The current implementation or the doc's description?

@danieleds For now, just change the `member_id` to `user_id`.

**Comment by edolix** [comment]
@danieleds running the `curl` example i get `"message":"Ttl can't be blank"`. You need to set a `ttl: number` in the request and it works

```sh
curl --location --request POST 'https://edoardogallo.signalwire.com/api/chat/tokens' \
--header 'Authorization: Basic <AUTH-HERE>' \
--header 'Content-Type: application/json' \
--data-raw '{"member_id":"my-unique-id","channels":{"my-channel-name":{"read":true,"write":true}}, "state":{}, "ttl": 30}'
```

**Comment by bryanrite** [comment]
FYI, on any 422, the response body will tell you what is wrong. Just look at the response:

```
{
    "errors": [
        {
            "type": "validation_error",
            "code": "missing_required_parameter",
            "message": "Ttl can't be blank",
            "attribute": "ttl",
            "url": "https://docs.signalwire.com/api/errors#missing_required_parameter"
        },
        {
            "type": "validation_error",
            "code": "invalid_parameter",
            "message": "Ttl is not a number",
            "attribute": "ttl",
            "url": "https://docs.signalwire.com/api/errors#invalid_parameter"
        }
    ]
}
```
